name: Deploy to Production
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy-production:
    name: Deploy production
    uses: AplinkosMinisterija/reusable-workflows/.github/workflows/biip-deploy.yml@main
    secrets: inherit
    permissions:
      contents: read
      packages: write
    with:
      environment: Production
      docker-image: ghcr.io/AplinkosMinisterija/ambulance-drivers-web
      build-args: REACT_APP_CLIENT_ID=8250078977a31f0d5733c53b501f7f69
